name: equiagents
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - tqdm
  - gym=0.21.0
  - pip
  - pip:
      - gym-factored==0.1.0
      - cvxpy==1.5.2
      - ecos==2.0.14
      - clarabel==0.9.0
      - scikit-learn==1.3.2
      - scikit-optimize==0.10.2
      - pyyaml
